version: "3.12.4"
services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DoLlitoS640M
      MYSQL_DATABASE: hh_data
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "8001:8001"
    depends_on:
      - db  
    networks:
      - my-net 
    volumes:
      - db-data:/var/lib/mysql   

  parser:
    build:
      context: ./parser 
      dockerfile: Dockerfile
    
    ports:
      - "8000:8000"
    command: python parser.py  
    depends_on:
      - db  
    networks:
      - my-net  
    volumes:
      - db-data:/var/lib/mysql  
  
  bot:
    build: ./bot
   
    depends_on:
      - backend    
    networks:
      - my-net  
  
networks:
  my-net:

volumes:
  db-data:


